---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bestz/public_html/filmtestsub.bestz.com
    - echo "Starting deployment..."
    - /bin/cp -R * $DEPLOYPATH/
    - echo "Deployment completed."
